# print("Hello World!")
# print("Python is fun!")
# print("All is well")
# #print("Hello World!");print("Python is fun!");print("All is well")
# print("Hello World!",end=" ")
# print("Python is fun!",end=" ")
# print("All is well")
# print(100)
print("Number of people in my class is:",15)